sudo: false
language: rust
rust:
- 1.31.0  # oldest supported version
- stable
- beta
matrix:
  include:
  - env: RUSTFMT
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt
    script:
      - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests
  - env: CLIPPY
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add clippy
    script:
      - cargo clippy --all-features

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo test  --verbose
# Audit `format` for new features.
- cargo test  --verbose --features "strict_unstable"

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
